services:
  app:
    build:
      context: ./
    env_file: .env
    container_name: rag-my-docs-app
    ports:
      - 3000:3000
  redis:
    image: redis/redis-stack-server
    volumes:
      - redis_data:/data
    container_name: rag-my-docs-redis
  pg:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data
    container_name: rag-my-docs-postgres
volumes:
  redis_data:
  pg_data:
